print ("This is my Python Code")
print ("This is my Python Code")
print ("This is my Python Code")
print ("This is my Python Code")
print ("This is my Python Code")
print ("This is my Python Code")
print ("This is my Python Code")
print ("This is my Python Code")
print ("Hi Abhishek")
